"""schema inicial V1

Revision ID: 1eb3a1232a49
Revises: 
Create Date: 2026-08-20 20:14:40.685971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb3a1232a49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'FECHADO', name='statuscaixa'), nullable=False),
    sa.Column('valor_abertura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_contado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacao_fechamento', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('pin_hash', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('perfil', sa.Enum('ATENDENTE', 'GERENTE', name='perfilfuncionario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('saldo_devedor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impressoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LIVRE', 'OCUPADA', name='statusmesa'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('impressora_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['impressora_id'], ['impressoras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('comandas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'FECHADA', 'CANCELADA', name='statuscomanda'), nullable=False),
    sa.Column('aberta_em', sa.DateTime(), nullable=False),
    sa.Column('fechada_em', sa.DateTime(), nullable=True),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('caixa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentos_caixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('SANGRIA', 'REFORCO', 'DESPESA', 'CONSUMO_FUNCIONARIO', name='tipomovimento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('registrado_em', sa.DateTime(), nullable=False),
    sa.Column('caixa_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quitacoes_consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_quitado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quitado_em', sa.DateTime(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('autorizado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autorizado_por_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forma', sa.Enum('CREDITO', 'DEBITO', 'DINHEIRO', 'PIX', 'CONSUMO_INTERNO', name='formapagamento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('registrado_em', sa.DateTime(), nullable=False),
    sa.Column('comanda_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_consumo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comanda_id'], ['comandas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_consumo_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_combo', sa.Boolean(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combo_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_comanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unit_congelado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.Column('motivo_cancelamento', sa.String(length=500), nullable=True),
    sa.Column('comanda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comanda_id'], ['comandas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_comanda')
    op.drop_table('combo_itens')
    op.drop_table('produtos')
    op.drop_table('pagamentos')
    op.drop_table('quitacoes_consumo')
    op.drop_table('movimentos_caixa')
    op.drop_table('comandas')
    op.drop_table('categorias')
    op.drop_table('mesas')
    op.drop_table('impressoras')
    op.drop_table('funcionarios')
    op.drop_table('caixas')
    # ### end Alembic commands ###
